ctoec/data-collection

src/data/users.ts, src/middleware/authenticate.ts, src/middleware/error.ts, src/models/user.ts, src/router/api.ts, src/types/custom.d.ts
=> Add user check and JWT authetication

package.json, src/middleware/authenticate.ts, src/middleware/error.ts, yarn.lock
=> Add file upload route

client/package.json, client/src/containers/Header/Header.tsx, client/src/containers/Upload/Upload.tsx, client/src/contexts/UserContext/UserContext.tsx, client/yarn.lock
=> Add form upload component and logout

README.md, package.json
Add minor setup specifics to the README, and specify that Node 12 is the version to be used in package.json.
=> README Updates

client/src/containers/GettingStarted/GettingStarted.tsx, client/src/containers/Home/Home.tsx, client/src/routes.ts
=> Add getting started page

docker-compose.yaml, package.json, src/index.ts, src/models/index.ts, src/models/problemDetails.ts, yarn.lock
should close #71 
and rider: removes ProblemDetails model, which is a holdover from .Net
=> Adds postgres backend

client/src/containers/Upload/Upload.tsx, client/src/generated/apis/DefaultApi.ts, client/src/generated/models/index.ts, package.json, src/controllers/report/ReportController.ts, src/models/enrollmentReport.ts, src/models/flattenedEnrollment.ts, src/models/index.ts, src/routes/routes.ts, src/services/enrollment/EnrollmentService.ts, src/services/report/ReportService.ts, swagger.json, yarn.lock
Should close #82 
Merge after #81
=> Implement CVS/XLSX parse for enrollment report

src/entity/FlattenedEnrollment.ts, src/entity/IncomeDetermination.ts, src/migration/1597328000967-UpdateIncomeFieldsMakeDecimal.ts
Also adds some changes to DB that were made to model for missing ENUM
types
=> Alters income fields in DB to be decimal, not integer

client/package.json, client/src/components/CSVDownloadLink.tsx, client/src/containers/CheckData/CheckData.tsx, client/src/containers/SubmitSuccess/SubmitSuccess.tsx, client/src/routes.ts, client/yarn.lock
Closes #25.
- https://github.com/ctoec/component-library/pull/43
=> UX Workflow to Submit Data to OEC

client/src/components/MailToLink.tsx, client/src/containers/App/App.scss, client/src/containers/App/App.tsx, client/src/index.scss, client/yarn.lock
=> Simplify header

client/yarn.lock
Remove the merge conflict committed to our `yarn.lock` by reinstalling the `component-library` dep based on the state of `package.json`.
=> Remove merge conflict in yarn.lock

client/src/containers/DataDefinitions/DataDefinitions.tsx
=> Removed sorting function

shared/models/Community.ts, shared/models/FundingSource.ts, shared/models/FundingTime.ts, shared/models/Organization.ts, shared/models/index.ts, src/entity/Community.ts, src/entity/Organization.ts, src/entity/enums/FundingSource.ts, src/entity/enums/FundingTime.ts, src/entity/index.ts
Closes #142 
Created a barebones community model in the shared directory, then implemented its interface as an Entity (followed the paradigm set by Organization here). I know Julia is working on a PR to eliminate the enums from the backend (and just rely on the shared dir), but since this wasn't committed yet I just followed what was there.
=> 142 readiness

client/src/containers/CheckData/CheckData.scss, client/src/containers/CheckData/CheckData.tsx, client/src/index.scss, src/routes/enrollmentReport.ts
=> Small tweaks

client/src/components/MailToLink.tsx
=> Correct mailto link

client/src/containers/EditRecord/Forms/CareForKidsForm.tsx
Closes #212 . Fixed a type casting error that was misidentifying the child object. The function should be able to run without issue now. Also added the legend for accessibility.
=> Fixed build types, added legend

client/src/utils/api.ts
Necessary to make the put updates work for the form objects
=> Add put helper to API backend

client/src/utils/api.ts, src/controllers/children.ts, src/controllers/sites.ts, src/entity/Community.ts, src/entity/Organization.ts, src/entity/Site.ts, src/index.ts, src/migration/1598459559085-Community.ts, src/routes/children.ts, src/routes/index.ts, src/routes/sites.ts, src/utils/parseQS.ts, src/utils/parseQueryString.ts, tsconfig.json
Also:
- adds QS parsing util
- adds some explicit Id props to entities to enable easier checking
without unnecessary object loading
- makes org -> community have an FK
- pulls children logic into controller file
- trims down the built resources with change to tsconfig
=> Adds /sites GET route

.circleci/config.yml
Temporary fix until my VPC refactor is done.
=> Fix CI Fawkes staging deploy

src/controllers/enrollmentReports/parse.ts, src/entity/FlattenedEnrollment.ts, src/entity/decorators/columnMetadata.ts
=> 232, 217: Improves excel parsing for dates and zipcodes

client/src/components/BackButton.tsx, client/src/containers/CheckData/CheckData.tsx, client/src/containers/DataRequirements/DataRequirements.tsx, client/src/containers/EditRecord/EditRecord.tsx
=> Add back button

client/src/containers/CheckData/CheckData.tsx, client/src/containers/CheckData/TableColumns.tsx, client/src/containers/DataRequirements/DataRequirements.tsx, client/src/containers/EditRecord/EditRecord.tsx, src/controllers/enrollmentReports/map.ts
=> 222 verify site

client/src/containers/App/App.tsx
Added the main element at the app level and a skip nav
=> Use main element and skip nav

client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/Forms/DeleteRecord.tsx, client/src/containers/EditRecord/Forms/EnrollmentFunding/Form/ChangeFundingForm.tsx, client/src/containers/EditRecord/Forms/EnrollmentFunding/Form/EditEnrollmentForm.tsx, client/src/containers/EditRecord/Forms/EnrollmentFunding/Form/EditFundingForm.tsx, client/src/containers/EditRecord/Forms/FamilyIncome/EditDeterminationForm.tsx, client/src/containers/EditRecord/Forms/FamilyIncome/Fields/DeterminationCard.tsx, client/src/containers/EditRecord/Forms/FamilyInfo/Fields/Homelessness.tsx, client/src/containers/EditRecord/Forms/FamilyInfo/Form.tsx, client/yarn.lock, src/entity/Enrollment.ts, src/entity/Funding.ts, src/migration/1599593076571-CascadingDelete.ts, src/migration/1599593850178-EnrollmentCascade.ts, src/routes/children.ts, src/routes/enrollments.ts, src/routes/families.ts, src/routes/fundings.ts
Closes #250 #283 #280 #279 #284
=> Delete individual components (income dets, fundings, etc.)

client/src/components/Forms/CareForKids/Form.tsx, client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/components/Forms/ChildInfo/Form.tsx, client/src/components/Forms/EnrollmentFunding/Form/index.tsx, client/src/components/Forms/FamilyAddress/Form.tsx, client/src/components/Forms/FamilyIncome/Form/index.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
=> 347 roster alert

client/src/containers/AddChild/AddChild.tsx, client/src/containers/Roster/Roster.scss, client/src/routes.ts, client/src/utils/getValidationStatus.ts, src/controllers/children.ts, src/entity/Child.ts, src/utils/distributeValidationErrorsToSubObjects.ts
Addresses PR comments that I missed before merging #358
=> PR comments

client/src/components/Forms/EnrollmentFunding/Fields/Funding/NewFunding.tsx, client/src/components/Forms/EnrollmentFunding/__snapshots__/EnrollmentFunding.test.tsx.snap, client/src/containers/CheckData/__snapshots__/CheckData.test.tsx.snap, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/shared/models/FundingSource.ts, src/controllers/enrollmentReports/map.ts, src/migration/1600383973776-InitialMigration.ts
=> Funding types

client/src/shared/models/FundingSource.ts, src/data/initialize.ts
=> 349 smart start state head start start dates

src/data/initialize.ts, src/index.ts
=> Determine application seeding by environment

client/src/containers/AddChild/AddChild.tsx, client/src/containers/CheckData/CheckData.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
=> Move alert elements and change roster back button

client/package.json, client/src/components/Forms/ChildIdentifiers/Fields/BirthCertificateFieldSet.tsx, client/src/components/Forms/ChildInfo/Fields/Race.tsx, client/src/components/Forms/FamilyAddress/Fields/AddressFieldset.tsx, client/src/components/Forms/FamilyIncome/Fields/IncomeDeterminationFieldSet.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/utils/getValidationStatus.ts, client/yarn.lock
Closes #390 
Depends on https://github.com/ctoec/component-library/pull/73
=> 390 error message copy

client/package.json, client/src/components/BackButton.tsx, client/src/containers/AddChild/AddChild.tsx, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, client/src/containers/GettingStarted/__snapshots__/GettingStarted.test.tsx.snap, client/src/containers/Roster/Roster.tsx, client/yarn.lock
Closes #454 
Closes #395 for real this time
Depends on https://github.com/ctoec/component-library/pull/75
=> Take two alerts

client/src/containers/Upload/CheckReplaceData.tsx, src/controllers/enrollmentReports/index.ts, src/controllers/enrollmentReports/removeExisting.ts, src/index.ts, src/middleware/error/errors.ts, src/routes/enrollmentReports.ts
=> 350: (PART II) upload replaces roster -- back end

client/package.json, client/src/components/Forms/ChildIdentifiers/Fields/BirthCertificateFieldSet.tsx, client/src/components/Forms/ChildIdentifiers/Fields/DateOfBirth.tsx, client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/components/Forms/ChildIdentifiers/__snapshots__/ChildIdentifiers.test.tsx.snap, client/src/components/Forms/ChildInfo/Form.tsx, client/src/components/Forms/ChildInfo/__snapshots__/ChildInfo.test.tsx.snap, client/src/components/Forms/EnrollmentFunding/__snapshots__/EnrollmentFunding.test.tsx.snap, client/src/components/Forms/FamilyAddress/Fields/AddressFieldset.tsx, client/src/components/Forms/FamilyAddress/__snapshots__/FamilyInfo.test.tsx.snap, client/src/containers/App/App.tsx, client/src/containers/EditRecord/WithdrawRecord/__snapshots__/WithdrawRecord.test.tsx.snap, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, client/src/containers/Upload/CheckReplaceData.tsx, client/src/index.scss, client/yarn.lock
Closes #455 
Depends on https://github.com/ctoec/component-library/pull/77
=> Adjust fieldset spacing

src/controllers/children.ts, src/utils/distributeValidationErrorsToSubObjects.ts
closes #470 
(Note the bug where there are no contract spaces / reporting period options remains -- it's a separate thing that i hope to fix soon with data cache)
=> 470: Fixes change enrollment failure

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/TableColumns.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap
=> 541 add missing info column

client/src/containers/Roster/RosterSectionHeader.tsx, client/src/containers/Roster/TableColumns.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Upload/Upload.tsx, src/controllers/enrollmentReports/map.ts, src/controllers/enrollmentReports/removeExisting.ts, src/routes/enrollmentReports.ts
=> 450 access control batch upload

client/src/components/Forms/FamilyIncome/Fields/DeterminationDate.tsx, client/src/containers/App/App.tsx
=> 519 remove default income determination

client/src/components/Forms/Enrollment/Fields/NewFunding.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/components/Forms/Enrollment/Funding/Fields/ContractSpace/ContractSpace.tsx, client/src/components/Forms/Enrollment/Funding/Fields/ReportingPeriod.tsx, client/src/components/Forms/Enrollment/Funding/Form.tsx, client/src/components/Forms/types.ts, client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/containers/EditRecord/EnrollmentFunding/EditEnrollmentCard.tsx, client/src/containers/EditRecord/EnrollmentFunding/EnrollmentFunding.tsx
Adds status funcs to reporting period and contract space
closes #586
=> 586: Implements fast follows from big PR

client/src/components/CSVExcelDownloadButton.tsx, src/routes/export.ts, src/routes/template.ts
Discovered this bug while writing tests-- needed to move the example download to an unauthenticated route.
=> Correct file download

client/src/components/Forms/Enrollment/Form.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx, client/src/containers/Roster/rosterUtils.tsx, src/controllers/children.ts, src/controllers/enrollmentReports/map.ts, src/data/initialize.ts
closes #613 
closes #578 
closes #485 
closes #608 
closes #570 
closes #611 
closes #607
=> 10 22 bugs

client/src/components/Forms/Enrollment/Funding/Form.tsx, client/src/containers/EditRecord/EnrollmentFunding/EditEnrollmentCard.tsx, client/src/containers/EditRecord/EnrollmentFunding/EditFundingCard.tsx, client/src/containers/EditRecord/WithdrawRecord/WithdrawRecord.tsx, client/src/containers/Roster/rosterUtils.tsx, client/src/shared/models/db/Enrollment.ts, src/entity/Enrollment.ts, src/migration/1603461371360-UpdateEnrollmentMakeSiteNullable.ts
closes #536 by actually making it possible to create an enrollment without a site.
=> 536: Make site nullable so enrollments can be created without site

src/controllers/enrollmentReports/parse.ts, src/routes/enrollmentReports.ts
closes #622 
also, with this change am not able to reproduce #621  or #624
=> 622: fix batch uupload

src/controllers/enrollmentReports/map.test.ts, src/controllers/enrollmentReports/map.ts
need to case numerical values for contract space from sheet to string before comparing to other string and doing string functions
and add testing for that
also resolve merge conflict resolution error that resulted in fundings being saved on `check` upload PUT (no objects should be saved!) which was throwing errors and messing with the check errors modal
=> Fix a last funding bug

client/package.json, client/src/index.tsx
Closes #551 
~Not ready for review just yet, gotta make a PR so I can use QA env in BrowserStack~
Edit: this appears to have fixed it, yay!
=> Fix ie thing, maybe

client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/components/Forms/ChildInfo/Form.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/components/Forms/Enrollment/Funding/Form.tsx, client/src/components/Forms/FamilyIncome/Form.tsx, client/src/components/Forms/types.ts, client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/containers/BatchEdit/EnrollmentFunding/Form.test.tsx, client/src/containers/BatchEdit/EnrollmentFunding/Form.tsx, client/src/containers/BatchEdit/EnrollmentFunding/__snapshots__/Form.test.tsx.snap, client/src/containers/BatchEdit/listSteps.tsx, client/src/containers/EditRecord/EnrollmentFunding/EditEnrollmentCard.tsx, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, client/src/containers/Roster/rosterUtils.tsx, client/src/containers/Roster/tableColumns.tsx, client/src/routes.ts, client/src/shared/models/db/Child.ts, src/controllers/children.ts, src/data/children.ts, src/entity/Child.ts, src/entity/decorators/Child/raceValidation.ts, src/entity/decorators/momentValidators.ts, src/utils/distributeValidationErrorsToSubObjects.ts, src/utils/raceFields.ts
Closes #480 
closes #566 
TODO: fixup tests, add tests
=> 480 single record batch edit

client/src/components/Forms/FamilyIncome/Form.tsx, client/src/components/Forms/FamilyIncome/FosterIncomeNotRequiredAlert.tsx, client/src/containers/EditRecord/FamilyIncome/Form.tsx, client/src/shared/models/db/Enrollment.ts, src/controllers/children.ts, src/entity/Child.ts, src/entity/Family.ts
=> 465 income det validation

client/package.json, client/src/components/AddRecordButton.tsx, client/src/components/CSVExcelDownloadButton.tsx, client/src/components/Forms/Enrollment/Fields/CareModel.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/components/Forms/FamilyIncome/Form.tsx, client/src/containers/CreateRecord/CreateRecord.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/GettingStarted/GettingStarted.tsx, client/src/containers/GettingStarted/__snapshots__/GettingStarted.test.tsx.snap, client/src/containers/Home/Home.tsx, client/src/containers/Home/__snapshots__/Home.test.tsx.snap, client/src/containers/Roster/MonthFilter/MonthFilterIndicator.scss, client/src/containers/Roster/MonthFilter/MonthFilterIndicator.tsx, client/src/containers/Roster/MonthFilter/MonthFilterModal.tsx, client/src/containers/Roster/Roster.scss, client/src/containers/Roster/Roster.test.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/RosterButtonsTable.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/rosterUtils.tsx, client/src/containers/Roster/tableColumns.tsx, client/src/containers/Roster/useRosterFilters.ts, client/src/containers/SubmitSuccess/__snapshots__/SubmitSuccess.test.tsx.snap, client/src/containers/Upload/ErrorModal/ErrorsModal.tsx, client/src/utils/models/childHasEnrollmentsActiveInMonth.ts, client/yarn.lock
Closes #548 and #560 
Depends on https://github.com/ctoec/component-library/pull/87
=> 548 month view

client/src/components/Forms/FamilyIncome/Form.tsx, client/src/components/Forms/FamilyIncome/__snapshots__/FamilyIncome.test.tsx.snap, client/src/containers/EditRecord/FamilyIncome/EditDeterminationCard.tsx
=> Family income bugs

client/src/containers/Upload/Upload.tsx
Closes #564 and fixes some spacing weirdness caused by other changes
=> Clear errors after user uploads another file

client/package.json, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/useGenerateUserSpecificProps.ts, client/src/containers/Upload/Upload.tsx, client/yarn.lock
Closes #499 
Depends on https://github.com/ctoec/component-library/pull/89
=> 499 loading

client/src/containers/CreateRecord/CreateRecord.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/Roster/Roster.test.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/index.tsx, client/src/containers/Roster/hooks/useChildrenWithErrorsAlert.tsx, client/src/containers/Roster/hooks/useOrgSiteProps.ts, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, client/src/containers/Roster/rosterUtils.tsx, client/src/hooks/useAuthenticatedSWR.ts, src/controllers/children/get.ts, src/entity/decorators/Enrollment/fundingAgeGroupValidation.ts, src/entity/decorators/Enrollment/fundingOverlapValidation.ts
=> 354 (pt III): actually paginate

client/src/containers/Upload/CheckReplaceData.tsx, client/src/containers/Upload/Upload.tsx, client/src/index.tsx
=> 702 upload cache stale

client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Form.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/__snapshots__/ChangeEnrollment.test.tsx.snap, src/controllers/children/changeEnrollment.ts
=> 698: Fix changeEnrollment for enrollment with funding

client/src/components/DataDefinitionsTable.tsx, client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/containers/CreateRecord/CreateRecord.tsx, client/src/containers/Roster/Roster.test.tsx, client/src/containers/Roster/rosterUtils.tsx, client/src/hooks/useValidationErrors.ts, client/src/utils/api.ts, src/controllers/children/create.ts, src/controllers/children/get.ts, src/middleware/error/errors.ts, src/middleware/error/handleError.ts, src/routes/children.ts, src/utils/validateObject.ts
=> 701 empty records

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/RosterSectionHeader.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/data/fundingSpace.ts, src/entity/FundingSpace.ts
=> Enforce -1 capacity for SHS spaces

src/data/initialize.ts, src/middleware/authenticate.ts
=> Add check for prodlike env

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/useOrgSiteProps.tsx, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, client/src/containers/Roster/rosterUtils.tsx, src/controllers/children/get.ts, src/routes/children.ts
=> 670: Add roster sub sub header and fix sub header text

src/controllers/children/create.ts, src/controllers/children/get.ts, src/controllers/enrollmentReports/map.test.ts, src/controllers/enrollmentReports/map.ts, src/controllers/enrollmentReports/mapUtils/child.ts, src/controllers/enrollmentReports/mapUtils/enrollment.ts, src/controllers/enrollmentReports/mapUtils/family.ts, src/controllers/enrollmentReports/mapUtils/funding.ts, src/controllers/enrollmentReports/mapUtils/incomeDetermination.ts, src/utils/validateObject.ts
- If site level user, filter for enrollments @ permitted sites OR site =
null and (enrollment author = the user or child author = the user) 
- adds user id to batch-uploaded records
- if missing-info = true, then don't apply any other filters -- return
all records with missing info, regardless of withdrawn status
- adds undefined check to `validateObject`
closes #774 
closes #766
=> 774: Update /children GET query filters

src/controllers/children/get.ts, src/controllers/enrollmentReports/mapUtils/child.ts, src/controllers/enrollmentReports/parse.ts, src/utils/filterSoftRemoved.ts
=> 762-714-child-get-fixes

client/src/components/Forms/ChildIdentifiers/ChildIdentifiers.test.tsx, client/src/components/Forms/ChildIdentifiers/Fields/UniqueId.tsx, client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/components/Forms/ChildIdentifiers/__snapshots__/ChildIdentifiers.test.tsx.snap, client/src/containers/EditRecord/EditRecord.test.tsx, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, src/controllers/enrollmentReports/mapUtils/child.ts, src/controllers/export.ts, src/template/EnrollmentReportRow.ts
=> 235 (Pt II): alter forms and parsing to account for different unique id

client/src/components/CSVExcelDownloadButton.tsx, client/src/components/Forms/FamilyIncome/Fields/IncomeDeterminationFieldSet.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/useChildrenWithErrorsAlert.tsx, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, client/src/containers/Roster/rosterUtils.tsx, client/src/containers/Roster/tableColumns.tsx, client/src/utils/models/getCurrentEnrollment.ts, client/src/utils/models/getLastEnrollment.ts
Closes #747 closes #740 
Also fixes a bug where the backend was incorrectly parsing withdrawn param and only ever returning withdrawn enrollments.
=> 747 740 withdrawn

client/public/config.json
Point Fawkes at new Winged Keys FQDN in production.
---------------------------------------------------------------------------------------------------------------------------
- https://github.com/skylight-hq/ctoec-devops/pull/152
- https://github.com/ctoec/winged-keys/pull/64
=> Update prod WingedKeys URL in Fawkes

client/package.json, client/src/containers/Upload/Upload.tsx, client/src/contexts/UserContext/UserContext.tsx, client/src/index.tsx, client/yarn.lock, src/routes/enrollmentReports.ts
~WIP, made this PR to be able to deploy to QA easily~
Closes #806 .  The IE problem is only half fixed here though :/
=> 794 ie batch upload

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, e2e-tests/package.json
Fast follows to fix some bugs with the roster button hiding (better matches AC now), single site view capacity (hides the ratio), and e2e tests (adds retries to combat their flakey nature).
Closes #682 
Closes #634 
Closes #593
=> Roster buttons and e2e fixes

client/src/containers/GettingStarted/GettingStarted.tsx, client/src/containers/GettingStarted/__snapshots__/GettingStarted.test.tsx.snap, src/data/initialize.ts
also, fixup delete to fix staging
closes #813
=> 813: fixup getting started collection period text and dates

client/package.json, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/RosterContent.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/useOrgSiteProps.tsx, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, client/src/containers/Roster/rosterUtils.tsx, client/src/contexts/UserContext/UserContext.tsx, client/yarn.lock, src/data/sites.ts
Closes #812 
Depends on https://github.com/ctoec/component-library/pull/98
=> 812 multi site tabnav fixes

client/src/containers/App/App.tsx, client/src/containers/App/ConfidentialityAgreement.tsx, client/src/containers/App/MakeRouteWithSubroute.tsx, client/src/containers/App/NotSignedInRedirect.tsx, client/src/contexts/UserContext/UserContext.tsx, client/src/index.scss
Closes #824 
Note: I think I'll need to add an e2e util before merging
=> Confidentiality agreement

client/src/contexts/UserContext/UserContext.tsx, client/src/shared/models/db/User.ts, src/entity/User.ts, src/middleware/authenticate.ts, src/migration/1606165287113-AddConfidentialityToUsers.ts, src/routes/users.ts
Closes #825 
Fast follow for #826 and branched from that PR
=> 825 one time confidentiality

client/src/components/DataDefinitionsTable/TableColumns.tsx, client/src/components/DataDefinitionsTable/utils.tsx, src/controllers/enrollmentReports/parse.ts, src/controllers/export.ts, src/routes/template.ts, src/template/EnrollmentReportRow.ts, src/utils/generateFiles/generateCsv.ts, src/utils/generateFiles/generateExcel.ts, src/utils/generateFiles/getFormattedColumnHeader.ts, src/utils/generateFiles/streamTabularData.ts
=> 846: Template update fast follows

client/src/containers/Upload/Upload.tsx
=> Add render key to file input

client/src/containers/Upload/Upload.tsx
=> 855: Clear error dict on every file upload

client/src/components/Forms/Enrollment/Fields/EnrollmentStartDate.tsx, client/src/components/Forms/Enrollment/Fields/NewFunding.tsx, client/src/components/Forms/Enrollment/Fields/Site.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/components/Forms/Enrollment/Funding/Fields/ContractSpace/ContractSpace.tsx, client/src/components/Forms/Enrollment/__snapshots__/Enrollment.test.tsx.snap, client/src/components/Forms/FamilyAddress/Form.tsx, client/src/components/Forms/FamilyAddress/__snapshots__/FamilyInfo.test.tsx.snap, client/src/components/Forms/FamilyIncome/Form.tsx, client/src/containers/CreateRecord/CreateRecord.tsx, client/src/containers/CreateRecord/listSteps.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/__snapshots__/ChangeEnrollment.test.tsx.snap, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/__snapshots__/ChangeFunding.test.tsx.snap, src/entity/Enrollment.ts, src/routes/enrollments.ts
Closes #859 and gets us to where we can at least add a child.  I made a few todo notes (that I will make into tickets) about some other bugs I ran into.
=> 859 add funding bug

client/src/components/Forms/ChildIdentifiers/Fields/BirthCertificateFieldSet.tsx, client/src/components/Forms/ChildIdentifiers/Fields/BirthState.tsx, client/src/components/Forms/ChildIdentifiers/Fields/BirthTown.tsx, client/src/components/Forms/ChildIdentifiers/Form.tsx, client/src/containers/EditRecord/DeleteRecord/__snapshots__/DeleteRecord.test.tsx.snap, client/src/containers/EditRecord/WithdrawRecord/__snapshots__/WithdrawRecord.test.tsx.snap, client/yarn.lock
=> Birth cert bugs

client/src/containers/Upload/Upload.tsx, client/src/utils/getFormDataBlob.ts
=> 794: Makes upload work in IE

client/src/components/DataDefinitionsTable/DataDefinitionsTable.tsx, client/src/components/DataDefinitionsTable/TableColumns.tsx, client/src/components/DataDefinitionsTable/utils.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Form.tsx, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, package.json, yarn.lock
=> 899 specific site

client/src/containers/App/App.tsx, client/src/containers/GettingStarted/GettingStarted.tsx, client/src/containers/GettingStarted/__snapshots__/GettingStarted.test.tsx.snap, client/src/containers/TemplateDownload/TemplateDownload.tsx, client/src/containers/Upload/ErrorModal/ErrorsModal.tsx, client/src/containers/Upload/ErrorModal/TableColumns.tsx, e2e-tests/utils/navigateToDataTemplate.js, yarn.lock
Closes #771  ...maybe? Was there more to this AC than is written in the ticket, or did we give it two points by mistake?
Closes #878 too
=> 771 reorder nav

client/package.json, client/src/containers/Home/Home.scss, client/src/containers/Home/Home.tsx, client/src/containers/Home/__snapshots__/Home.test.tsx.snap, client/yarn.lock, e2e-tests/tests/deleteChild.js, e2e-tests/tests/smoke.js, e2e-tests/utils/uploadFile.js, src/controllers/children/changeEnrollment.ts, src/controllers/enrollmentReports/mapUtils/enum.ts, src/middleware/error/passAsyncError.ts
Closes #876 
Depends on https://github.com/ctoec/component-library/pull/101
=> Use correct arrow

client/src/components/CSVExcelDownloadButton.tsx, client/src/containers/Home/Home.tsx, client/src/containers/TemplateDownload/TemplateDownload.tsx, client/src/contexts/AuthenticationContext/useAuthConfig.ts, client/src/shared/constants/FundingSourceTimes.ts, client/src/shared/models/FundingSourceTime.ts, e2e-tests/tests/deleteChild.js, e2e-tests/utils/downloadTemplateOrExample.js, e2e-tests/utils/navigateToDataTemplate.js, e2e-tests/utils/uploadFile.js, src/data/fake/children.ts, src/data/fake/enrollment.ts, src/data/fake/family.ts, src/data/fake/fundingSpace.ts, src/data/fake/incomeDeterminations.ts, src/data/fake/utils.ts
Closes #874 
~JK forgot to modify sample data-- will ping in slack when this is no longer a draft~ Ready for review!
=> 874 data template

client/src/components/DataDefinitionsTable/DataDefinitionsTable.tsx, client/src/components/DataDefinitionsTable/TableColumns.tsx, client/src/components/DataDefinitionsTable/utils.tsx, client/src/containers/DataRequirements/DataRequirements.tsx, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap
=> 905: Removes warning about 07/2020 from data defn table

client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx
=> 904: Complete state in batch edit

client/src/components/Forms/Enrollment/Fields/NewFunding.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/components/Forms/Enrollment/__snapshots__/Enrollment.test.tsx.snap, client/src/components/Forms/FamilyIncome/Form.tsx, client/src/components/Forms/FamilyIncome/__snapshots__/FamilyIncome.test.tsx.snap, client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/containers/BatchEdit/EnrollmentFunding/Form.test.tsx, client/src/containers/BatchEdit/EnrollmentFunding/Form.tsx, client/src/containers/BatchEdit/EnrollmentFunding/__snapshots__/Form.test.tsx.snap, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/__snapshots__/ChangeEnrollment.test.tsx.snap, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/__snapshots__/ChangeFunding.test.tsx.snap, e2e-tests/utils/enterFormValue.js
Closes #937 closes #785 closes #800  also fixes bug where family income wasn't saving at all in batch edit
=> 937 blank batch

client/src/utils/formatters/fundingSpace.ts
=> Accommodate temporary lack of week values

client/src/containers/CreateRecord/CreateRecord.tsx, e2e-tests/tests/newChild.js, e2e-tests/tests/newIncompleteChild.js, e2e-tests/tests/uploadMissingOne.js, e2e-tests/tests/uploadMissingSome.js, e2e-tests/utils/enterFormSection.js, e2e-tests/utils/enterFormValue.js
Addresses error where validation errors were not shown in create child bc section was only marked visited upon success.  Adds e2e test.
=> Validation errors add child

client/package.json, client/src/components/Forms/ChildIdentifiers/__snapshots__/ChildIdentifiers.test.tsx.snap, client/src/components/Forms/Enrollment/__snapshots__/Enrollment.test.tsx.snap, client/src/components/Forms/FamilyAddress/__snapshots__/FamilyInfo.test.tsx.snap, client/src/components/Forms/FamilyIncome/__snapshots__/FamilyIncome.test.tsx.snap, client/src/containers/EditRecord/DeleteRecord/DeleteRecord.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/__snapshots__/ChangeEnrollment.test.tsx.snap, client/src/containers/EditRecord/WithdrawRecord/WithdrawRecord.tsx, client/src/containers/EditRecord/WithdrawRecord/__snapshots__/WithdrawRecord.test.tsx.snap, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, client/src/containers/Roster/MonthFilterModal.tsx, client/src/containers/Upload/CheckReplaceData.tsx, client/src/containers/Upload/ErrorModal/ErrorsModal.tsx, client/src/containers/Upload/Upload.tsx, client/yarn.lock
Closes #978 
Depends on https://github.com/ctoec/component-library/pull/108
=> 978 upload x file clear

src/data/prod/README.MD, src/data/prod/create.ts, src/data/prod/invite.ts, src/data/prod/organizations.ts
adds programmatic user invitation and fixes up funding space to account for PT/FT splits
=> Invite user programatic

client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/containers/CreateRecord/CreateRecord.tsx, client/src/containers/EditRecord/DeleteRecord/DeleteRecord.tsx, client/src/containers/EditRecord/DeleteRecord/__snapshots__/DeleteRecord.test.tsx.snap, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Form.tsx, client/src/containers/EditRecord/WithdrawRecord/WithdrawRecord.tsx, client/src/containers/Roster/tableColumns.tsx, client/src/utils/formatters/name.ts
=> Use name formatter

client/src/components/DataDefinitionsTable/TableColumns.tsx
=> 994: Formats data requirement field names properly

client/src/containers/Roster/rosterUtils/getChildrenWithErrorsAlert.tsx, e2e-tests/utils/uploadFile.js
=> Update missing info alert text

client/src/containers/Home/Home.tsx, client/src/containers/Home/PostSubmit.tsx
Fixes infinite load state  for post-submit users  and prevents flashing for pre-submit users. Tested by login of non-submitted user, refreshing home, going to every tab nav page and  back, refreshing on  tab nav pages then going to home, then doing it all again after uploading and submitting. Didn't see anything weird on local. Closes #1022 .
=> Fix load bug

src/controllers/children/delete.ts, src/controllers/enrollmentReports/removeExisting.ts, src/data/fake/children.ts, src/data/fake/enrollment.ts, src/data/fake/family.ts, src/entity/Child.ts, src/entity/Enrollment.ts, src/entity/Family.ts
=> 1024: Fixes soft deletes

client/src/containers/Landing/Landing.tsx, client/src/containers/Landing/__snapshots__/Landing.test.tsx.snap
=> 1032: Points privacy policy link to correct location

client/src/containers/Home/PreSubmit.tsx, src/loggers/RequestLogger.ts
closes #1030  to remove a little bit of kruft from the logs
=> 1030: filter  logging to only include api requests

client/src/containers/EditRecord/EditRecord.scss, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/Card.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/ChangeFunding.test.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/Form.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/__snapshots__/ChangeFunding.test.tsx.snap
=> Update funding form button alignment and wording

client/package.json, client/src/integrationTests/children.test.ts, client/src/integrationTests/enrollments.test.ts, client/src/integrationTests/incomeDetermination.test.ts, client/src/integrationTests/utils.ts, client/src/integrationTests/validations.test.ts, src/controllers/enrollments.ts, src/entity/Enrollment.ts, src/entity/decorators/Funding/fundingBeginsAfterEnrollmentEntry.ts, src/entity/decorators/Funding/lastReportingPeriodValidation.ts
Also, rounds out enrollment and funding validation tests
closes #945
closes #1072
=> Makes api integration tests reliable

client/package.json, client/src/components/DataDefinitionsTable/DataDefinitionsTable.tsx, client/src/components/DataDefinitionsTable/RequirementLevelLegend.tsx, client/src/containers/DataRequirements/DataRequirements.tsx, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, client/yarn.lock
Closes #996.
- https://github.com/ctoec/component-library/pull/114
=> Make sections on Data-Requirements page navigable

src/controllers/enrollmentReports/removeExisting.ts
Bug revealed by user's data disappearing!
https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1096
on my local i:
- uploaded data for a bunch of orgs as an org-level user
- switched to site-level user with only subset of site permissions
- uploaded data, choosing to replace data for "all sites"
- switched back to org-level user and confirmed data for other sites (that site user could not access) was untouched
=> 1096: ensures enrollment report for site-level user will only overwrite their sites

client/package.json, client/src/containers/EditRecord/FamilyIncome/EditDeterminationCard.tsx, client/src/containers/EditRecord/FamilyIncome/Form.tsx, client/yarn.lock
Incomes with the value of $0 were not displaying correctly in forms or text. This was due to two separate errors where we failed to account for number types with the value of 0 as valid values.
#1099 
https://github.com/ctoec/component-library/pull/125
Changed the default value in storybook default value textinput example. We could also write a test either here or in the component library.
=> 1099 income zero

client/package.json, client/yarn.lock
Updates component library. Will  need to replace with published lib after that PR is approved.
https://github.com/ctoec/component-library/issues/127
https://github.com/ctoec/component-library/pull/128
We could write an e2e test for changing enrollment that leverages this behavior
=> New component lib version

client/src/containers/DataRequirements/DataRequirements.tsx, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap
We're giving providers an extra weekend to submit their data, so the app should say as much.
https://github.com/ctoec/data-collection/issues/1183
- https://github.com/ctoec/ece-reporter-support/pull/4
Point your eyeballs at the date on the Data Requirements page.
=> Update Data Submission Deadline

client/package.json, client/src/components/Forms/Enrollment/Fields/Site.tsx, client/src/components/Forms/Enrollment/Form.tsx, client/src/containers/BatchEdit/__snapshots__/BatchEdit.test.tsx.snap, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Form.tsx, client/src/containers/Home/Home.test.tsx, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, client/src/containers/Roster/Roster.test.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/integrationTests/children.test.ts, client/src/integrationTests/enrollments.test.ts, client/src/integrationTests/incomeDetermination.test.ts, client/src/integrationTests/oecReport.test.ts, client/src/integrationTests/revision.test.ts, client/src/integrationTests/validations.test.ts, client/tsconfig.json, client/yarn.lock
Stuff got messed up for reasons I cannot figure out right now. This resolves things. 
https://github.com/ctoec/data-collection/issues/1207
https://github.com/ctoec/data-collection/issues/1206
N/A
LETS GET THIS MERGED SO WE CAN HAVE CI/CD AGAIN ! :)
=> Fixes tests,updates react-scripts,things should be ok

client/src/containers/Upload/Preview.tsx, src/controllers/enrollmentReports/formatUploadPreview.ts, src/controllers/enrollmentReports/map/mapUtils/incomeDetermination.ts, src/controllers/enrollmentReports/parse/parseUtils.ts, src/routes/enrollmentReports.ts
Provide a brief overview of the work completed here.
https://github.com/ctoec/data-collection/issues/1201
https://github.com/ctoec/data-collection/issues/1220
I KNOW I DID UN-SCOPED/SPRINTED WORK but tbh i had a lot of these fixes sitting on my local already from testing/debugging user uploads so it felt like they were just freeeeeeeeeeeee please forgive me @JordanGuinn
=> 1201 income det value parse

client/src/containers/Overview/SiteSummaryTabNav.tsx, client/src/containers/Overview/SiteSummaryTable.tsx, src/controllers/summary.ts
I didn't validate in an env that had > 0 sites without any data b/c my brain just isn't 100 today at all. 
Also fix a missing letter (complete vs completed)
https://github.com/ctoec/data-collection/issues/243
=> 243: Fixup query again

client/src/containers/App/App.tsx
As i mentioned, I am without a brain today at this moment. Realized we needed to hide these nav bits from the admin user, because they are not for the admin user and will 
#243
=> 243: hide primary program-user-specific nav items

src/controllers/children/get.ts
Using the `Export roster` button on the roster page would throw 500.
https://github.com/ctoec/data-collection/issues/1296
Validated locally
=> Fix roster export bug

client/package.json, client/yarn.lock, package.json, yarn.lock
Yarn audit reporting errors.
N/A
N/A
=> Update packages to fix vulnerabilities

src/controllers/organizations.ts
Fix site count when no funding space is on an org
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.
=> Change sql query from fs.organizationid to o.id

client/src/containers/Users/EditUser.tsx, client/src/containers/Users/Users.tsx, client/src/containers/Users/UsersTable.tsx, client/src/routes.ts, src/controllers/users.ts, src/routes/users.ts
Added user edit page for name information
#1281 
UI:
=> Edit users name
