azure-pipelines.yml
Ensures that all of our CI pipeline phases that require yarn installs use the exact version specified in `yarn.lock`, and not whatever the latest version allowed by `package.json` is.
=> Update all CI execution steps to install from yarn lockfile

README.md, client/tsconfig.json, ormconfig.js, package.json, shared/models/Child.ts, shared/models/Family.ts, shared/models/Gender.ts, shared/models/SpecialEducationServicesType.ts, shared/models/index.ts, src/entity/Child.ts, src/entity/Enrollment.ts, src/entity/EnrollmentReport.ts, src/entity/Family.ts, src/entity/FlattenedEnrollment.ts, src/entity/Funding.ts, src/entity/FundingSpace.ts, src/entity/FundingTimeSplit.ts, src/entity/IncomeDetermination.ts, src/entity/Organization.ts, src/entity/Permission.ts, src/entity/ReportingPeriod.ts, src/entity/Site.ts, src/entity/User.ts, src/entity/decorators/dataDefinition.ts, src/migration/1597692652273-AlterChildAlterFamilyMatchDataCollection.ts, tsconfig.json
- enums are only defined in shared/models/enums, not also in server
- renamed Unspecified to NotSpecified so that all gender enum options
start with a different letter, which makes parsing the
FlattenedEnrollment into child a little bit easier and why not
- server now transpiles shared node_module because it was all of a
sudden getting mad and unable to find the module without this
- so, updates references to built `dist/` resources to be at `dist/src`
- adds special ed fields to child
- condenses addressLine1 and addressLine2 into streetAddress on family
- makes all server entity models in `src/entity` extend the appropriate interfaces from
`shared/models`
=> Some changes to models

buildspec.test.yml, buildspec.yml, client/package.json, client/src/containers/App/App.test.tsx, client/yarn.lock
There is a [known Yarn issue](https://github.com/yarnpkg/yarn/issues/7212) (described in more detail [here](https://github.com/yarnpkg/yarn/issues/7212#issuecomment-493720324)) in which the installation of dependencies utilizing `prepare` scripts results in multiple yarn processes running concurrently and one of them inevitably failing.  We still need to build `component-library` on install though (assuming we want to iteratively and quickly develop against it at times), so we're now getting around this by [throttling yarn's concurrent request cap](https://github.com/yarnpkg/yarn/issues/7212#issuecomment-487930971).
Most definitely a workaround, but it works for now.
=> Workaround for race condition between yarn install and component-library build

shared/models/FundingSource.ts, shared/models/FundingTime.ts, src/entity/enums/AgeGroup.ts, src/entity/enums/FundingSource.ts, src/entity/enums/FundingTime.ts, src/entity/enums/Gender.ts, src/entity/enums/Region.ts, src/entity/enums/index.ts
Closes #121 and Closes #122 
It looks like there isn't any standardization between the funding times of various funding sources. For example, different funding sources reference "full day" and "school day," which sound like the same thing but are currently treated separately. Same thing with "expanded day." I'm guessing this is an artifact of the agencies / funding sources rather than something by design on our end, but should we be handling this in any specific way? As in, is it feasible for us to consolidate these different names for the same things down into one 'type' (i.e. full day and school day both now just refer to 'full day')?
=> Added new funding types to enums

docker-compose.yaml
Within local development, Express serves the React app based on the host/port as it exists _within the Docker container_ (3000).  And because we don't use Docker anywhere but during local development, there's no need to expose the static React app outside of the container.  (It can also cause confusion as to what the actual entrypoint to the application should be 😅)
=> Remove local port mapping of React app

client/src/contexts/AuthenticationContext/AuthenticationContext.tsx
Token refresh is triggered by Auth context on every render, but only
actually makes the request if the token is about to expire.
closes #178
=> 178: Avoid jwt expired error by having AuthorizationContext trigger token refresh

client/src/containers/CheckData/CheckData.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/contexts/AuthenticationContext/AuthenticationContext.tsx, client/src/routes.ts
Assuming the TabNav PR in the component library gets approved, here's the blank field form navigation from the edit roster page. UI is a work in progress but this at least lets us start getting forms created. Also, as we make them, we can refactor the currently hardcode TabNavProps objects in the middle of CheckData to be their own module entities.
=> Skeleton tabnav to put forms in

client/package.json, client/src/containers/CheckData/CheckData.tsx, client/src/containers/CheckData/TableColumns.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/Upload/Upload.tsx, client/src/routes.ts, client/yarn.lock, src/entity/Child.ts, src/routes/children.ts, src/routes/index.ts, src/utils/mapFlattenedEnrollment.ts
Adds a DB save to the mapping step, and returns all data
as a nested child object, as opposed to a flat map of all object
Also adds an endpoint to GET a single child, and uses that for the
"Edit-Record" view
Also fixes client routing from upload to check data
=> Persists parsed flattened enrollment data to DB

client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/Forms/CareForKidsForm.tsx
Not ready to merge, but like Melanie, I thought it would be good to get this up where it can be seen. I know we're blocked on the ticket because of the API, but if we're happy with this way of storing change back in the object I'll move forward with that (the idea is that while the individual Forms in the TabNav can save fields in the Child object representing a row, the EditRecord page will have a button below all the forms for Save & Return to CheckData that will handle the API PUT request).
=> Care4Kids Info Form

src/controllers/fundingSpaces.ts, src/controllers/sites.ts, src/entity/FundingSpace.ts, src/entity/Organization.ts, src/entity/User.ts, src/middleware/authenticate.ts, src/migration/1598580605137-AlterFundingSpaceFixUnqiueConstraint.ts, src/routes/fundingSpaces.ts, src/routes/index.ts, src/routes/sites.ts
adds service to retrieve all funding spaces a user has access to
also:
- updates user to have orgIds (all orgs the user can access, including those owned by communities user can access) and siteIds (all sites the user can access, including those owned by orgs they have access to, or orgs owned by communities they have access to) instead of sites property
- simplifies the site service, removing the siteId/organizationId/communityId filtering b/c we dont need it yet and why do i always build things we dont need 
- adds unique constraint on user.wingedKeysId
- correct unique constraint on funding space table to include organization id
=> Add service for funding-spaces

client/src/components/EditForms/ChildIdentifiers/Fields/DateOfBirth.tsx, client/src/components/EditForms/ChildIdentifiers/__snapshots__/ChildIdentifiers.test.tsx.snap, client/src/containers/AddChild/AddChild.tsx, client/src/containers/AddChild/ListSteps.tsx, client/src/containers/AddChild/NewFamilyIncome.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/WithdrawRecord/index.tsx, client/src/routes.ts, client/yarn.lock, src/controllers/children.ts, src/controllers/enrollmentReports/map.ts, src/entity/Child.ts, src/routes/children.ts, src/routes/families.ts
For consistency with other API access patterns, make children POST return just 201 created with id, then have the API do another GET.
Remove childId from create-record path because it is not actually needed (page maintains child obj as state var, which has id once it exists). Having id in the path would enable the user to navigate back here if they lost connection etc during middle of create flow _BUT_ this won't work because organization is required, and is passed in via Link navigation to the page. So at some point, we want to decide what should happen if the user navigates to the add record page not from the right place (should they get an informative message? or just be redirected to the roster?) 
also:
- adds back incorrectly removed defaultValue null for birthdate (shouldn't default …
=> Child POST returns id for fetch pattern consistency

client/src/containers/Upload/Upload.tsx, client/src/utils/handleJWTError.ts
Closes #209 
This does the bare minimum to address the issue.  Some open questions:
- After someone logs in, should we redirect them to getting started (current behavior) or take them back to what they were trying to access?
- Should we somehow poll for log-in-ed-ness and automatically redirect people to the logged out screen after a certain period of time?
- How far do we want to go on winged keys branding to make this whole experience less confusing?
=> Handle jwt error for file upload

client/src/containers/AddChild/AddChild.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/tabItems.tsx
Merged #446 a little too hastily-- the alerts were under the h1 but they were messing with layout of the links in edit child/accidentally subject to flexbox
=> Correct alert placement for edit record

client/src/containers/FundingSourceTimes/FundingSourceTimes.tsx
Reformats the table of funding types and contract spaces to use contract spaces as the row indexer for each column (this forces the accepted format text to line up with each contract space). Funding types are then broadcast over multiple rows.
Closes #618
=> Correct table spacing

.circleci/config.yml
Necessary because Docker is gonna start rate limiting image pulls, and we don't want to drastically reduce our CI/CD capacity.
**Associated PR:** https://github.com/skylight-hq/ctoec-devops/pull/133
=> Use our own custom images in CircleCI deploys

.ebextensions/https-instance.config
This hack has since been [moved to Terraform](https://github.com/skylight-hq/ctoec-devops/pull/150), so at least it lives in one place and not three.
---------------------------------------------------------------------------------------------------------------------------
- https://github.com/skylight-hq/ctoec-devops/pull/150
- https://github.com/ctoec/ecis-experimental/pull/1281
- https://github.com/ctoec/winged-keys/pull/63
=> Remove default EC2 security group deletion hack

src/controllers/children/get.ts, src/utils/filterSoftRemoved.ts
Makes soft delete filtering handle if `family`  is undefined, as well as  if  the rows to filter on are  undefined. Closes #770 .
closes #768 
closes #767
=> Handle nulls/undefineds

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, src/controllers/enrollments.ts, src/routes/enrollments.ts, src/routes/families.ts
Disables submitting to OEC while the app isn't live, and also adds some org ID checks to object creation / updates / gets.
Closes #634 
Closes #779 
I might be missing some of the context for the Org ID check ticket because where I was looking, it seems like we already mostly have that in place (i.e. the child controllers do org checks, the funding controller does checks, most of the routes already filter, etc.). I just wound up updating families, income determinations, and enrollments (although that might've been the point in hindsight).
=> Disable submit when not in prod

src/controllers/enrollmentReports/mapUtils/child.ts
Closes #792 
The `instanceof` check in the `isIdentifierMatch` function was receiving `object` as the child's class type instead of Child. Moved child creation outside of a conditional so that the child that's pushed into the already-seen array has the proper prototype value to compare against because `instanceof` is a funky and likes to complain.
=> Enforce stronger typing to make instanceof work

src/controllers/enrollmentReports/map.ts, src/controllers/enrollmentReports/mapUtils/child.ts, src/data/initialize.ts, src/middleware/authenticate.ts, src/migration/1605749736657-UpdateOrganizationFixUniqueIdTypeDefault.ts, src/routes/enrollmentReports.ts
1. Closes #792 
- fixes bad default value in organization table for uniqueIdType column 
- fixes is identifier match check by doing double-equals comparison of sasid/unique id fields to account for null/undefined 
- Fixes up the update child stuff so that we don't try to save entities when we shouldn't and all entities that need Ids have them 
~1. Reduces the number of network requests the Roster page makes:
- condenses the withdrawn/active enrollments request into one, since we always get both from the roster home page
- makes the useOrgSiteProps hook return things as state variable, which for whatever reason drastically cut down on number of requests issued~ this turned into a melodrama, and we will figure out a more robust fix not at 11 pm
~1. Makes sure that on refetch of data, all …
=> Tweaks 11/18

client/src/components/Forms/Enrollment/Form.tsx, client/src/containers/EditRecord/EditRecord.tsx, client/src/containers/EditRecord/EnrollmentFunding/Form.tsx, client/src/containers/EditRecord/__snapshots__/EditRecord.test.tsx.snap, src/entity/Child.ts, src/entity/decorators/Child/fundedEnrollmentValidation.ts
put this on top of error boundary b/c it was easier so will make sure that gets merged first.
need eyes on how to do something with the missing funding alert, in absence of the funding card with missing info icons. threw placeholder error alert in there for now. 
closes #489 
closes #580
=> 489: Add validation for funded enrollment requirement

client/src/containers/DataRequirements/DataRequirements.test.tsx, client/src/containers/PrivacyPolicy/PrivacyPolicy.test.tsx, client/src/containers/Roster/Roster.test.tsx, client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, client/src/containers/Roster/rosterUtils.tsx, src/controllers/children/get.ts, src/routes/children.ts
since we always fetch all of the enrollments anyway; might as well save the duplicative work
Also fixes a bug where children with no enrollments were no showing up
in the roster ever
also makes roster tests mock smarter
=> Do withdraw filtering in the frontend,

e2e-tests/README.md, e2e-tests/utils/headerMatch.js, e2e-tests/utils/login.js, e2e-tests/utils/scrollToElement.js
Adds a util into the login function that lets e2e tests accept the confidentiality agreement (if they need to for a particular run). Also, it looks like a *significant* portion of the e2e tests were failing due to the login identifying the wrong title, so I changed how that got parsed to find the landing page `h1`.
=> Accept confidentiality agreement

src/routes/template.ts
Issue was caused by having two `res.send()` calls, resulting in the system trying to unexpectedly send a response after one response was already formatted and written (`streamTabularData` sets the content type and sends, and then the route was trying to send again with an empty body because `streamTabularData` doesn't return anything, which created the `cannot Remove headers` bug). Closes #835 .
=> Fix header error

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/hooks/useChildrenWithErrorsAlert.tsx
Closes #969 
There's still a little delay where the alert shows, I think bc of how caching is working (i.e. for the same reason that we see stale children values for a mo' when the roster loads).
=> Set alerts to empty array if there are no children with errors

client/src/containers/EditRecord/EditRecord.tsx
Closes #967 
@RyanHansz I took the AC to mean that there should only be one alert showing when funding info is missing-- even if there is other info missing.  Is that what you meant?
=> Only show one alert for missing funding

src/entity/IncomeDetermination.ts, src/migration/1608582587797-AddIncomeNotDisclosedToFamily.ts
wondering how others feel about the merits of having validation errors around "incomeNotDisclosed" ? I don't know that it actually is useful, but maybe it is? happy to put it back, since this change to the DML prevents the bad state
=> Adds values for existing income dets

src/entity/Enrollment.ts, src/routes/enrollmentReports.ts
Fixes a parsing bug where conditional validations would crash on enrollments that tried to parse fundings with errors. I can't be sure this is what caused the specific user error in the ticket, but the log output from the same problem that de-railed a qa e2e test makes it seem like this should do the trick.
As far as adding a timestamp to the file name, I tried changing that in a couple places and got `cannot change _file.name because it is a read-only property`, so I'm not sure where the best place to try to add a timestamp is. Persisting to disk is handled here, but any advice on where in the code is the right place to append a timestamp?
Associated Ticket: https://github.com/ctoec/component-library/issues/121
=> Fix upload parsing error

client/src/containers/Roster/Roster.scss, client/src/containers/Roster/RosterSectionFundingSpacesMap.tsx, client/src/containers/Roster/RosterSectionHeader.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/rosterUtils/getAccordionItems.tsx
The funding space headers of each age group in the roster accordion are textually cluttered, making it hard to see at a glance what the filled status of each funding space is. This PR cleans up those headers to more succinctly display capacity information.
https://github.com/ctoec/data-collection/issues/671
I've uploaded several different files featuring all the different funding spaces and have checked that names and counts get correctly displayed. Also tested that showing and hiding an accordion group hides the space totals info.
Since the AC of the ticket asked for the space totals information to be hidden when the age group accordion is collapsed, I've moved the "header" portion into the content itself. This visually looks almost identical to me, but it seemed like the best way for …
=> Clean up funding spaces text in header

client/src/components/Forms/Enrollment/Fields/NewFunding.tsx, client/src/containers/CreateRecord/listSteps.tsx, e2e-tests/utils/newChildInput.js, src/controllers/enrollments.ts, src/routes/enrollments.ts
Fixes bug described in #605 by adding or modifying fundings in enrollment edit endpoint. Fixes bug where existing funding source was not selected on page refresh in radio button group.
#605 
Also addresses #1133 
-
Follow steps as described in 605 or, to shortcut this and not go through the entire create child flow, click on a child with incomplete information and replace "edit" with "create" in the URL.
-
=> 605 first reporting period

client/src/containers/Roster/Roster.tsx, client/src/containers/Roster/hooks/usePaginatedChildData.tsx, src/controllers/children/get.ts, src/entity/decorators/Funding/fundingOverlapValidation.ts
Our funding space overlap validator currently breaks when comparing a given funding with all the other fundings within an organization and **at least one** of those fundings is missing a reporting period start date.  This PR addresses that.
- #1137
N/A
N/A
=> Address Funding Space Overlap Bug

client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/containers/EditRecord/EnrollmentFunding/Form.tsx
There are two quick fast follows fixes that involve tweaking up some UI aspects of the tool. This PR sorts funding cards so that the most current one is at the top, grays out the backgrounds of expired funding cards, and pushes an alert to the roster page if a user comes from a single record batch edit.
#273 
#657 
I tested the new batch edit functionality with a variety of single record batch edits and confirmed that it works when using the traditional batch edit on multiple records. I got the correct alert state in each case.
=> Fix up batch edit and funding cards

src/data/fake/initialize.ts
Ignore the funding space ID value when inserting seed data so we don't attempt to insert ID values that have since been added and removed (because we auto-increment).
- N/A
- N/A
- N/A
=> Ignore Funding Space ID in test env seeders

client/package.json, client/src/containers/BatchEdit/BatchEdit.tsx, client/src/containers/BatchEdit/BatchEditItemContent.tsx, client/src/hooks/useAuthenticatedSWR.ts, client/yarn.lock
Use swr config option to not revalidate on window focus so that we don't re-fetch children with missing info. Re-fetching was preventing us from displaying completed records in side nav.
#1145 
Follow detailed steps in ticket
=> 1145 batch edit

client/src/components/Forms/Enrollment/Fields/NewFunding.tsx, client/src/containers/EditRecord/EnrollmentFunding/EditFundingCard.tsx, client/src/containers/Home/utils/mapFundingSpacesToCards.tsx, client/src/containers/Roster/RosterSectionFundingSpacesMap.tsx, client/src/containers/Roster/__snapshots__/Roster.test.tsx.snap, client/src/containers/Roster/tableColumns.tsx, client/src/setupTests.ts
This PR removes the acronym from the funding source text in all the places that it's appropriate to.  Just... it's fine.
- https://github.com/ctoec/data-collection/issues/635
N/A
Look at all parts of the application where funding sources reside (besides the data requirements page and upload template) and ensure the acronyms are gone.
=> Forcibly trim funding source acronyms from funding sources

client/src/utils/formatters/fundingSpace.ts
Update our funding space formatter to remove the `(## weeks)` text from all funding spaces across the application.
- https://github.com/ctoec/data-collection/issues/1178
N/A
Navigate through the application and confirm that `(## weeks)` is not present in any views where funding spaces are displayed.
=> Remove "weeks" from all funding spaces

client/package.json, client/src/containers/BatchEdit/__snapshots__/BatchEdit.test.tsx.snap, client/src/containers/DataRequirements/__snapshots__/DataRequirements.test.tsx.snap, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, client/tsconfig.json, client/yarn.lock
Updates our version of `react-scripts` to address a [known vulnerability with a nested dependency](https://github.com/facebook/create-react-app/issues/9469) of that package ([similar issue captured here](https://github.com/facebook/create-react-app/issues/10411), too).  Necessary so that the audit portion of our CircleCI builds succeed again (the front-end `yarn audit` step was previously failing 100% of the time), and we can continue running our unit tests regularly.
Also updates snapshots/unit tests that were previously failing but we didn't know about because of the audit failures.
N/A
N/A
Ensure the application can be successfully deployed.  Given this is nothing but dependency version bumping, not sure what validation would otherwise look like.
=> Remove nested immer vulnerability in react-scripts dependency

src/loggers/RequestLogger.ts
causes type error which kills node proc. A problem in pre-prod, because this clears  + reseeds database, which should only happen on an intentional deploy or restart. 
https://github.com/ctoec/data-collection/issues/1147
=> 1147: Resolves transient error that kills node process

src/entity/Child.ts
Just removed the validating decorator that checks for birthdays < 12 years old
#1223
=> rm ed <12yo birthday upload validation

src/controllers/enrollmentReports/map/mapUtils/funding.ts, src/controllers/enrollmentReports/parse/parseUtils.ts
Reporting periods suck because they don't align with normal month by month dates, and this makes a big headache for users. The mapping between reporting period dates and the dates they write in their sheets is completely opaque and does not need to cause them stress. This PR address a weakness in reporting period mapping by: 
1. not automatically mapping all parsed reporting period fields to have 'startOfMonth' as their day value
2. first checking if a user supplied date is "meaningful" and finding a reporting period whose start and end dates sandwich the user date (makes more sense in the code comments)
3. if a user didn't supply a day value, making sure that the found reporting period is the right one to cover their given reporting period date …
=> Make RP months align with user entered dates

ormconfig.js
Our current CloudWatch logs are ~99% SQL queries at this point, making it very difficult to find any other more meaningful logs.  This PR disables SQL logs across the board so we can do so moving forward.
N/A
N/A
=> Disable SQL logging by default

src/controllers/enrollmentReports/map/mapUtils/incomeDetermination.ts
Right now, '"incomeNotDisclosed" value is ignored if income, householdsize, or determination date are provided.
Instead, accept all user input and allow them to define "income not disclosed" regardless of other values. 
#1238 
N/A
=> 1238: accepts income not disclosed even if other values are provided

src/routes/enrollmentReports.ts
When a user attempts an upload and their data has errors, it is very hard to diagnose their issues. This adds logging (with redacted PII) to hopefully make it easier for us to debug + resolve data errors without requiring users to send us their data files.
#1212 
N/A
Confirm logging in deployed envs when upload with errors is attempted
=> 1212: Log children with errors when upload has errors

client/src/containers/Home/Home.test.tsx, client/src/containers/Home/Home.tsx, src/controllers/oecReport.ts, src/routes/oecReport.ts
This PR addresses the inefficiency of making an API call for each org a user is associated with, changing that instead to be a single API call that uses different SQL to fetch and check all accessible organizations at once.
https://github.com/ctoec/data-collection/issues/1190
- https://github.com/skylight-hq/ctoec-devops/pull/206
Validation involved testing the home page as both a pre and a post-submit user. I ensured that the correct number of API calls were made in each case, and that the page was correctly shown to a user based on their submission status.
=> Make single endpoint instead of multiple calls

client/src/components/Forms/ChildInfo/ChildInfo.test.tsx, client/src/components/Forms/Enrollment/Enrollment.test.tsx, client/src/components/Forms/Enrollment/Funding/Funding.test.tsx, client/src/components/Forms/FamilyIncome/FamilyIncome.test.tsx, client/src/containers/BatchEdit/EnrollmentFunding/Form.test.tsx, client/src/containers/EditRecord/DeleteRecord/DeleteRecord.test.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/ChangeEnrollment.test.tsx, client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/ChangeFunding.test.tsx
Hopefully straightforward quixfix for tests' types.
I fixed an issue with my VSCode where I now check types project-wide on save. Errors related to these changes came up. At first I dismissed them figuring my project-wide config was broken. It kind of is in that it checks these types while our `tsc` doesn't. But the types _are_ wrong. So updating them here.
=> Fixed misc test types

src/controllers/summary.ts
First pass at this naively grabbed all children in the system. Later testing/review revealed that this should actually just be the total number of children *with a current, active enrollment*
#1246 
N/A
Jay wants to invite OEC users to the tool on thursday, so there's a bit of a due date on this
=> 1246: Update child count in admin view to include only children with active enrollment

client/src/integrationTests/children.test.ts, src/controllers/children/get.ts, src/routes/children.ts
Now on active children, previously on all children
Used the existing `getActiveChildren` fn and abstracted the query so we can now get the `count` and `children`, which should then be identical 
#1195 
N / A
Seems like the issue is around withdrawn children, so:
=> Fixed postsub count

client/package.json, client/yarn.lock
[Vulnerability found](https://github.com/webpack-contrib/terser-webpack-plugin/issues/388) with the version of `ssri` used by `webpack`, referenced by `react-scripts`.  This bumps that specific hotfix version of `ssri` used exclusively by `webpack` to [the version where this is fixed](https://github.com/npm/ssri/issues/18), until they get around to it.
N/A
If applicable, replace this text with links to additional pull requests associated with this work.
=> Bump SSRI version used by Webpack

client/src/containers/PrivacyPolicy/PrivacyPolicy.tsx, client/src/containers/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap
Turns out none of the links in our Privacy Policy actually _work_, at the moment.  This fixes that!
N/A
=> Fix Privacy Policy Links

client/package.json, package.json
The Docker executors our build/deploy/tests workflows run in on CircleCI have a pretty limited memory ceiling (given we're using the free version of CircleCI).  With that in mind, this PR adds the `--runInBand` parameter to our Jest unit test commands, which, [per Jest documentation](https://jestjs.io/docs/cli#--runinband), runs `"all tests serially in the current process, rather than creating a worker pool of child processes that run tests"`.  This also appears to have the added bonus of somehow [speeding up our total unit test execution time slightly](https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server)!
https://github.com/ctoec/data-collection/issues/1227
=> Reduce unit test memory usage

.circleci/config.yml, .ebextensions/https-instance.config, client/public/config.json, e2e-tests/nightwatch.conf.js
This PR adds support for running our ECE Reporter e2e tests in our new dedicated `automation` environment.
N/A
- https://github.com/skylight-hq/ctoec-devops/pull/214
- https://github.com/ctoec/winged-keys/pull/73
=> Create new automation environment for e2e tests

client/package.json, client/yarn.lock
Modals sometimes don't sit highest on the browser window - this PR should fix that.
https://github.com/ctoec/component-library/issues/133
https://github.com/ctoec/component-library/pull/148
=> Bump z-index of all modals

client/src/containers/Upload/PreviewChanges.tsx, client/src/shared/payloads/EnrollmentReportUploadResponse.ts, src/routes/enrollmentReports.ts
Based on the maprows refactor. A fast-follow/more involved conversation on the ranking of Withdrawn versus the other tags in the upload count. @bamader 's [thoughts here](https://github.com/ctoec/data-collection/pull/1285#issuecomment-839293301) seem reasonable.
So this ranking would be new > withdrawn > updates. Open to more thoughts. I don't personally have strong opinions, and I didn't want to block the other PR.
(It should be a 1 line change.)
#1324 
Please outline the steps you've already taken to validate this body of work, along with any additional steps that need to be taken in order to complete testing.
=> Upload withdrawn count

scripts/rebuild.sh, src/data/fake/initialize.ts
This PR fixes a race condition with our test environment seeder.  Previously, we decided whether or not to create funding spaces for a particular organization based on if there were _any_ rows in the funding space table **at all**.  This was problematic, because occasionally the creation of funding spaces for one organization would take place prior to the creation of funding spaces for another.  And in those scenarios, because we already had data in that table, we would simply not create any funding spaces for all remaining organizations.
We no longer do that, instead checking to see if there are any funding spaces for the organization we're currently dealing with to determine whether or not they need to be created.
ALSO, I shimmied in a tiny fix to the `rebuild.sh` script, from when it …
=> Fix funding space seeder bug

src/controllers/export.ts
The export function currently does not export SASIDs or Unique IDs saved on children to the resulting spreadsheet. This PR fixes that.
https://github.com/ctoec/data-collection/issues/1367
- Log into ECE Reporter
- Upload a child record
- Add or edit the SASID information for that child in the roster, and save the changes
- Export the roster
- Check the resulting spreadsheet for the successfully output SASID/UniqueId
The issue was happening because export works using a `hasOwnProperty` call. Our template has a `sasidUniqueId` field that jointly bundles these two, but `child` objects have only `sasid` and `uniqueId` fields, so the `hasOwnProperty` check was returning false. We just needed a special case to handle a template property that doesn't map to any entity.
=> Export unique IDs

client/src/containers/CreateRecord/CreateRecord.tsx
Check validation plan comment at the bottom to weigh in on discovered bugs before merging.
When refreshing on the Roster page and then hitting "Add Record", an error was shown. This was due to a bug in `CreateRecord.tsx` that wiped some state associated with the `history`. (Thanks @jlhogan for the fix!)
https://github.com/ctoec/data-collection/issues/1272
N/A
Followed reproduction steps in the issue and validated that the bug is no longer.
If there's anything additional information that those reviewing or validating this work should be aware of, please specify it here.
=> Fix post-refresh "Add Record" bug 

client/src/containers/App/AdminRedirect.tsx, client/src/containers/App/MakeRouteWithSubroute.tsx, client/src/containers/Organizations/Organizations.tsx, client/src/containers/Overview/Overview.tsx, client/src/containers/Users/EditUser.tsx, client/src/containers/Users/Users.tsx, client/src/routes.ts
This PR moves the handling of whether or not a user is an admin from the individual components to the centralized router. We no longer need to check this at every page/component-level because the router will handle it for us with a redirect.
https://github.com/ctoec/data-collection/issues/1347
Log in as an admin user and ensure you can reach:
Now, log in as a non-admin user, and ensure you can reach:
Additionally, ensure that non-admin users cannot reach (via direct page navigation) any of the admin pages:
This changeset doesn't affect routes that have `unauthorized: true`, because if we're not securing them then it doesn't matter if admins and non-admins can both reach them (this is true for pages like privacy policy and data template).
=> Centralize admin redirect to router
